### ISSUE TITLE
Handling Overflow

### ISSUE THREAD

**Issue by omus** [JuliaMath/FixedPointDecimals.jl#12]
Currently a `FixedDecimal` value can overflow since internally we are using integer math.
```julia
julia> import FixedPointDecimals: FD

julia> reinterpret(FD{Int8,2}, typemax(Int8))
FixedDecimal{Int8,2}(1.27)

julia> ans + reinterpret(FD{Int8,2}, 1)
FixedDecimal{Int8,2}(-1.28)
```
We should include some kind of system, maybe `checked_*` operations, so that users can choose how overflow is handled. We definitely do not want to ban the overflow behaviour.

**Comment by TotalVerb** [comment]
Checked operations sound like a good idea to me, as that's consistent with how `Int`s work.

**Comment by DatName** [comment]
Would like to bump this issue. Just stumbled upon
```
julia>  FixedDecimal{Int64, 12}(1) * 10000000
FixedDecimal{Int64,12}(-8446744.073709551616)
```
which was unexpected for me.

**Comment by NHDaly** [comment]
https://github.com/JuliaMath/FixedPointDecimals.jl/pull/85
