### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by TotalVerb** [JuliaMath/FixedPointDecimals.jl#4]
Once we're satisfied with the repo state, we should tag a release (on @attobot) so that Currencies can properly migrate.

**Comment by omus** [comment]
Will do. Was waiting for any objections in https://github.com/JuliaMath/Roadmap.jl/issues/6 first. I'll make sure to tag a feature equalivalent version to what is in Currencies v0.8.0

**Comment by omus** [comment]
Tagged v0.0.1
