### ISSUE TITLE
`convert(::FD{T,N}, ::Int128)` and `convert(::FD{T,N}, ::UInt128)` allocate `BigInt`s

### ISSUE THREAD

**Issue by Drvi** [JuliaMath/FixedPointDecimals.jl#83]
For example
```julia
julia> using FixedPointDecimals

julia> @time convert(FixedDecimal{Int,2}, Int128(1))
  0.000005 seconds (7 allocations: 128 bytes)
FixedDecimal{Int64,2}(1.00)
```
allocates a `BigInt` because a `widemul` is used to carry out the multiplication between the coefficient and the `Int128` value during the conversion.
This is problematic performance-wise.

One workaround would be to convert the coefficient to an `Int128` and then use `Base.mul_with_overflow`, throwing an `InexactError`  manually on overflow.

**Comment by NHDaly** [comment]
Fixed in https://github.com/JuliaMath/FixedPointDecimals.jl/pull/84.
